Document: mariadb-10.5.9-arm64
Title: Debian mariadb-10.5.9-arm64 Manual
Author: <insert document author here>
Abstract: This manual describes what mariadb-10.5.9-arm64 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mariadb-10.5.9-arm64/mariadb-10.5.9-arm64.sgml.gz

Format: postscript
Files: /usr/share/doc/mariadb-10.5.9-arm64/mariadb-10.5.9-arm64.ps.gz

Format: text
Files: /usr/share/doc/mariadb-10.5.9-arm64/mariadb-10.5.9-arm64.text.gz

Format: HTML
Index: /usr/share/doc/mariadb-10.5.9-arm64/html/index.html
Files: /usr/share/doc/mariadb-10.5.9-arm64/html/*.html
